Imports System.Drawing
Imports System.Text.RegularExpressions
Imports MySql.Data.MySqlClient

Public Class frmcreateuser

    Private Sub frmcreateuser_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.TopMost = True
        frmMain.Enabled = False

        ClearErrorLabels()
        LoadRoles()

        txtUsername.Tag = "AutoGenerated"
    End Sub

    Private Sub LoadRoles()
        cboRole.Items.Clear()
        cboRole.Items.Add("-- Select Role --")
        cboRole.Items.AddRange(New String() {
            "HR Staff",
            "HR Specialist",
            "HR Officer",
            "HR Manager",
            "Recruiter", "Talent Acquisition"
        })
        cboRole.SelectedIndex = 0
    End Sub

    Private Sub UpdateUsernameSuggestion() Handles txtFirstname.TextChanged, cboRole.SelectedIndexChanged
        If txtUsername.Tag Is Nothing OrElse txtUsername.Tag.ToString() <> "AutoGenerated" Then Exit Sub

        If String.IsNullOrWhiteSpace(txtFirstname.Text) OrElse cboRole.SelectedIndex <= 0 Then
            txtUsername.Clear()
            Exit Sub
        End If

        Dim cleanFirst As String = txtFirstname.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim cleanRole As String = cboRole.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim shortRole As String = If(cleanRole.Length >= 4, cleanRole.Substring(0, 4), cleanRole)
        Dim suggestedUser As String = $"{cleanFirst}{shortRole}"

        If suggestedUser.Contains("admin") Then
            suggestedUser = suggestedUser.Replace("admin", "usr")
        End If

        Try
            connection()
            Dim counter As Integer = 1
            Dim checkUser As String = suggestedUser

            Do
                sql = "SELECT Username FROM users WHERE Username=@uname"
                cmd = New MySqlCommand(sql, cn)
                cmd.Parameters.AddWithValue("@uname", checkUser)
                dr = cmd.ExecuteReader()

                If Not dr.HasRows Then
                    dr.Close()
                    Exit Do
                End If
                dr.Close()

                checkUser = $"{suggestedUser}{counter}"
                counter += 1
            Loop

            txtUsername.Text = checkUser
            txtUsername.SelectionStart = txtUsername.TextLength

        Catch ex As Exception
            txtUsername.Text = suggestedUser
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtUsername.KeyPress
        txtUsername.Tag = "ManualEdited"
    End Sub

    Private Sub txtConfirmPass_TextChanged(sender As Object, e As EventArgs) Handles txtConfirmPass.TextChanged, txtPassword.TextChanged
        If String.IsNullOrWhiteSpace(txtPassword.Text) AndAlso String.IsNullOrWhiteSpace(txtConfirmPass.Text) Then
            lblPassStatus.Text = ""
            lblPassStatus.Visible = False
            Return
        End If

        lblPassStatus.Visible = True
        If txtPassword.Text.Trim() = txtConfirmPass.Text.Trim() Then
            lblPassStatus.Text = "✓ Password Match"
            lblPassStatus.ForeColor = Color.Green
        Else
            lblPassStatus.Text = "✗ Password does not match"
            lblPassStatus.ForeColor = Color.Red
        End If
    End Sub

    Private Sub ClearErrorLabels()
        HideError(lblLastname)
        HideError(lblErrFirstname)
        HideError(lblErrUsername)
        HideError(lblErrRole)
        HideError(lblErrConfirmPass)
    End Sub

    Private Sub ShowError(lbl As Label, msg As String)
        lbl.Text = msg
        lbl.ForeColor = Color.Red
        lbl.Visible = True
    End Sub

    Private Sub HideError(lbl As Label)
        lbl.Text = ""
        lbl.Visible = False
    End Sub

    Private Function ValidateInputs() As Boolean
        Dim isValid As Boolean = True
        ClearErrorLabels()

        If String.IsNullOrWhiteSpace(txtLastname.Text) Then
            ShowError(lblLastname, "Lastname is required")
            isValid = False
        End If

        If String.IsNullOrWhiteSpace(txtFirstname.Text) Then
            ShowError(lblErrFirstname, "Firstname is required")
            isValid = False
        End If

        Dim lowerUsername As String = txtUsername.Text.Trim().ToLower()
        If String.IsNullOrWhiteSpace(txtUsername.Text) Then
            ShowError(lblErrUsername, "Username is required")
            isValid = False
        ElseIf lowerUsername.Contains("admin") Then
            ShowError(lblErrUsername, "Username cannot contain 'admin'")
            isValid = False
        End If

        If cboRole.SelectedIndex <= 0 Then
            ShowError(lblErrRole, "Role is required")
            isValid = False
        ElseIf cboRole.Text.ToLower().Contains("admin") Then
            ShowError(lblErrRole, "Admin accounts are not allowed")
            isValid = False
        End If

        If String.IsNullOrWhiteSpace(txtPassword.Text) Then
            ShowError(lblErrConfirmPass, "Password is required")
            isValid = False
        ElseIf txtPassword.Text.Length < 6 Then
            ShowError(lblErrConfirmPass, "Minimum 6 characters")
            isValid = False
        End If

        If String.IsNullOrWhiteSpace(txtConfirmPass.Text) Then
            ShowError(lblErrConfirmPass, "Confirm password is required")
            isValid = False
        ElseIf txtPassword.Text.Trim() <> txtConfirmPass.Text.Trim() Then
            ShowError(lblErrConfirmPass, "Password does not match")
            isValid = False
        End If

        Return isValid
    End Function

    Private Sub btnSubmit_Click(sender As Object, e As EventArgs) Handles btnSubmit.Click
        If LoggedRole <> "Administrator" AndAlso LoggedRole <> "System Admin" Then
            MsgBox("Access Denied! Only Administrator can add new users.", MsgBoxStyle.Exclamation)
            Return
        End If

        If Not ValidateInputs() Then
            Exit Sub
        End If

        Dim fullName As String = $"{txtLastname.Text.Trim()}, {txtFirstname.Text.Trim()}"

        Try
            connection()

            sql = "SELECT FullName FROM users WHERE FullName=@fullname"
            cmd = New MySqlCommand(sql, cn)
            cmd.Parameters.AddWithValue("@fullname", fullName)
            dr = cmd.ExecuteReader()

            If dr.HasRows Then
                dr.Close()
                ShowError(lblErrFirstname, "Full Name already exists")
                CloseConnection()
                Return
            End If
            dr.Close()

            sql = "INSERT INTO users (FullName, Username, PasswordHash, Role, Status) " &
                  "VALUES (@fullname, @uname, @pass, @role, 'Active')"

            cmd = New MySqlCommand(sql, cn)
            With cmd.Parameters
                .AddWithValue("@fullname", fullName)
                .AddWithValue("@uname", txtUsername.Text.Trim())
                .AddWithValue("@pass", txtPassword.Text.Trim())
                .AddWithValue("@role", cboRole.Text.Trim())
            End With

            cmd.ExecuteNonQuery()
            MsgBox("Successfully Registered!", MsgBoxStyle.Information, "Success")

            ClearForm()

        Catch ex As MySqlException
            If ex.Number = 1062 Then
                ShowError(lblErrUsername, "Username already exists")
            Else
                MsgBox("Database Error: " & ex.Message, MsgBoxStyle.Critical)
            End If
        Catch ex As Exception
            MsgBox("Error: " & ex.Message, MsgBoxStyle.Critical)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub ClearForm()
        txtLastname.Clear()
        txtFirstname.Clear()
        txtUsername.Clear()
        txtUsername.Tag = "AutoGenerated"
        txtPassword.Clear()
        txtConfirmPass.Clear()
        If cboRole.Items.Count > 0 Then cboRole.SelectedIndex = 0
        lblPassStatus.Text = ""
        lblPassStatus.Visible = False
        ClearErrorLabels()
    End Sub

    Private Sub btnClose_Click(sender As Object, e As EventArgs) Handles btnClose.Click
        If MsgBox("Are you sure you want to cancel?", MsgBoxStyle.YesNo Or MsgBoxStyle.Question, "Cancel") = MsgBoxResult.Yes Then
            ClearForm()
            Me.Hide()
            frmMain.Enabled = True
            frmMain.TopMost = True
            Me.TopMost = False
        End If
    End Sub

End Class